[colors.bright]
black = "0x{{colors.surface_bright.default.hex_stripped}}"
blue = "0x{{harmonized_colors.blue.hex_stripped}}"
cyan = "0x{{harmonized_colors.cyan.hex_stripped}}"
green = "0x{{harmonized_colors.green.hex_stripped}}"
magenta = "0x{{harmonized_colors.magenta.hex_stripped}}"
red = "0x{{harmonized_colors.red.hex_stripped}}"
white = "0x{{colors.on_surface_variant.dark.hex_stripped}}"
yellow = "0x{{harmonized_colors.yellow.hex_stripped}}"

[colors.normal]
black = "0x{{colors.surface.default.hex_stripped}}"
blue = "0x{{harmonized_colors.blue.hex_stripped}}"
cyan = "0x{{harmonized_colors.cyan.hex_stripped}}"
green = "0x{{harmonized_colors.green.hex_stripped}}"
magenta = "0x{{harmonized_colors.magenta.hex_stripped}}"
red = "0x{{harmonized_colors.red.hex_stripped}}"
white = "0x{{colors.on_surface.dark.hex_stripped}}"
yellow = "0x{{harmonized_colors.yellow.hex_stripped}}"

[colors.primary]
foreground = "0x{{colors.on_surface.default.hex_stripped}}"
background = "0x{{colors.surface.default.hex_stripped}}"

[colors.cursor]
cursor = "0x{{colors.on_surface.default.hex_stripped}}"
text = "0x{{colors.on_surface_variant.default.hex_stripped}}"

[colors.selection]
text = "0x{{colors.on_primary.default.hex_stripped}}"
background = "0x{{colors.primary_fixed_dim.default.hex_stripped}}"
